/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.BasketController;
import control.VareController;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import util.Listeners;

/**
 *
 * @author Mark
 */
public class Gui2 extends javax.swing.JFrame implements ActionListener {

    private CardLayout cl;
    private VareController vc;
    private BasketController bc;
    private Listeners listeners;

    /**
     * Creates new form Gui2
     */
    public Gui2() {
        bc = BasketController.getInstance();
        listeners = Listeners.getList();
        vc = VareController.getInstance();
        initComponents();
        vc.showVare(jPVarePanel);
        listeners.addListener(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPSalg = new javax.swing.JPanel();
        jPVarePanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPKurvPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPSalg.setLayout(null);

        jPVarePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Vare:"));

        javax.swing.GroupLayout jPVarePanelLayout = new javax.swing.GroupLayout(jPVarePanel);
        jPVarePanel.setLayout(jPVarePanelLayout);
        jPVarePanelLayout.setHorizontalGroup(
            jPVarePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );
        jPVarePanelLayout.setVerticalGroup(
            jPVarePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );

        jPSalg.add(jPVarePanel);
        jPVarePanel.setBounds(0, 0, 440, 450);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Kurv:"));

        jScrollPane1.setBorder(null);

        javax.swing.GroupLayout jPKurvPanelLayout = new javax.swing.GroupLayout(jPKurvPanel);
        jPKurvPanel.setLayout(jPKurvPanelLayout);
        jPKurvPanelLayout.setHorizontalGroup(
            jPKurvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
        );
        jPKurvPanelLayout.setVerticalGroup(
            jPKurvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 197, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPKurvPanel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPSalg.add(jPanel1);
        jPanel1.setBounds(440, 0, 340, 220);

        getContentPane().add(jPSalg, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPKurvPanel;
    private javax.swing.JPanel jPSalg;
    private javax.swing.JPanel jPVarePanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae) {
        switch (ae.getActionCommand()) {
            case "Tilføjet Til Kurv":
                bc.showBasket(jPKurvPanel);
                break;

        }
    }
}
