/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.BasketController;
import model.Drikkelse;
import model.DrikkelseTilSalg;

/**
 *
 * @author Mark
 */
public class KurvPanel extends javax.swing.JPanel {
    private BasketController bc;
    private DrikkelseTilSalg dts;

    /**
     * Creates new form KurvPanel
     */
    public KurvPanel(DrikkelseTilSalg d) {
        this.dts = d;
        bc = BasketController.getInstance();
        initComponents();
        jLNavn.setText(dts.getDrikkelse().getNavn());
        jLANtal.setText(dts.getAntal()+"");
        jLPris.setText(dts.getPris()+"");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBPlus = new javax.swing.JButton();
        jBMinus = new javax.swing.JButton();
        jLNavn = new javax.swing.JLabel();
        jLANtal = new javax.swing.JLabel();
        jLPris = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(380, 60));
        setLayout(null);

        jBPlus.setText("+");
        jBPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPlusActionPerformed(evt);
            }
        });
        add(jBPlus);
        jBPlus.setBounds(2, 0, 50, 40);

        jBMinus.setText("-");
        jBMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMinusActionPerformed(evt);
            }
        });
        add(jBMinus);
        jBMinus.setBounds(60, 0, 50, 40);

        jLNavn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLNavn.setText("Vand");
        add(jLNavn);
        jLNavn.setBounds(120, 0, 117, 40);

        jLANtal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLANtal.setText("x2");
        add(jLANtal);
        jLANtal.setBounds(250, 0, 30, 40);

        jLPris.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLPris.setText("399 Kr.");
        add(jLPris);
        jLPris.setBounds(290, 0, 60, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void jBPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPlusActionPerformed
        bc.basketPlus(dts.getDrikkelse());
    }//GEN-LAST:event_jBPlusActionPerformed

    private void jBMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMinusActionPerformed
        bc.basketMinus(dts.getDrikkelse());
    }//GEN-LAST:event_jBMinusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBMinus;
    private javax.swing.JButton jBPlus;
    private javax.swing.JLabel jLANtal;
    private javax.swing.JLabel jLNavn;
    private javax.swing.JLabel jLPris;
    // End of variables declaration//GEN-END:variables
}
